'use client'
import { useEffect, useState } from 'react'
import { disablePush, hasPushRegistration, pushSupportMessage, registerPush, type WebPushConfig } from '../lib/web-push'
import { functions } from '../lib/firebase'
import { httpsCallable } from 'firebase/functions'
export function PushNotifications({ employeeId }: { employeeId: string }) {
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [enabled, setEnabled] = useState(false); const [allowed, setAllowed] = useState(false); const [checking, setChecking] = useState(true)
  useEffect(() => { let alive = true; const support = pushSupportMessage(); setMessage(support); setChecking(true); httpsCallable<undefined, WebPushConfig>(functions, 'getWebPushConfig')().then(result => { if (alive) setAllowed(result.data.canRegisterPush ?? true) }).catch(error => { if (alive) setMessage(error instanceof Error ? error.message : '取得推播設定失敗') }).finally(() => { if (alive) setChecking(false) }); if (!support && Notification.permission === 'granted' && hasPushRegistration()) { setBusy(true); void registerPush().then(() => { if (alive) { setEnabled(true); setMessage('此裝置已開啟通知。') } }).catch(error => { if (alive) setMessage(error.message || '通知註冊失敗，請重試。') }).finally(() => { if (alive) setBusy(false) }) } return () => { alive = false } }, [employeeId])
  const enable = async () => { const support = pushSupportMessage(); if (support) { setMessage(support); return }; if (!allowed) { setMessage('目前未開放測試員工開啟通知。'); return }; setBusy(true); try { const permission = await Notification.requestPermission(); if (permission !== 'granted') { setMessage('尚未允許通知；若已封鎖，請到瀏覽器或手機設定開啟。'); return }; await registerPush(); setEnabled(true); setMessage('此裝置已開啟通知，關閉 App 後也可接收廣播。') } catch (error) { setMessage(error instanceof Error ? error.message : '通知註冊失敗，請重試。') } finally { setBusy(false) } }
  return allowed ? <div><button className="primary" disabled={busy} onClick={() => void enable()}>{busy ? '通知設定中…' : enabled ? '更新通知註冊' : '開啟通知'}</button>{enabled && <button disabled={busy} onClick={() => { setBusy(true); void disablePush().then(() => { setEnabled(false); setMessage('此裝置已停止接收通知。') }).catch(() => setMessage('關閉通知失敗，請重試。')).finally(() => setBusy(false)) }}>關閉此裝置通知</button>}<p role="status">{message}</p></div> : <p role="status">{checking ? '檢查推播權限中…' : message || '目前僅測試白名單可開啟手機推播。'}</p>
}
